### ISSUE TITLE
discord.js

### ISSUE THREAD

**Issue by Last-SilverLight-End** [strong-trash/huck-chatbot#1]
discord.js 로 만드실 건가요 아니면 카톡에 뿌리실 건가요

**Comment by wonjinYi** [comment]
본래는 간단한 웹프로그램으로 만들 생각이었는데요, 다른 환경에서 돌아가는 것도 좋을 것 같아요.

이 리포지토리가 모든 환경별 구현 프로그램의 배포판을 담도록 하면 어떨까요?
각 환경의 구현 프로그램별로 담당자를 두고 기술적/언어학적으로 의미있는 오픈소스로 발전시키면 좋겠습니다.

리포지토리를 아래와 같은 구조로 구성하는 것을 제안드립니다.

```
[root]
ㄴ [web]
    ㄴ (파일, 폴더, ..) : 웹에서 동작하는 프로그램의 모든 구성 요소( 코드, 이미지 등 )
ㄴ [discord]
    ㄴ (파일, 폴더, ..) : 디스코드에서 동작하는 프로그램의 모든 구성 요소( 코드, 이미지 등 )
```

만약 같은 환경에서 동작하는 프로그램이더라도 구현하고자 하는 바가 다르면, 
아래와 같이 별개의 프로그램을 만들어도 좋겠습니다.

```
[root]
ㄴ [web-wonjin]
ㄴ [web-sanghyun]
ㄴ [discord]
```

**Comment by Last-SilverLight-End** [comment]
그러면 무슨 말을 하든
무조건 적으로 huck 을 출력해서 말하면 되는 건가요

**Comment by Last-SilverLight-End** [comment]
아 혹시 헉 랭귀지 인건가요 전 무슨 말을 하든 헉을 내보내는줄 알았는데

**Comment by wonjinYi** [comment]
마음대로 하세요
